name: caribe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logotipo.png
    - assets/images/logotipo_largo.png
    - assets/images/profile_picture.jpg
    - assets/images/profile_pictures/ana_martinez.jpg
    - assets/images/profile_pictures/carlos_gonzalez.jpg
    - assets/images/profile_pictures/juan_perez.jpg
    - assets/images/crafts/alebrije_colorido.jpg
    - assets/images/crafts/mascara_madera.jpg
    - assets/images/crafts/rebozo.jpg
    - assets/images/crafts/sombrero_charro.jpg
    - assets/images/crafts/talavera.jpeg
