// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj76cfiIgZRk_lpGhpHgvEqQp9jCX_1VY',
    appId: '1:758475553455:web:3868bf7407b46ba90a725a',
    messagingSenderId: '758475553455',
    projectId: 'caribe-6d583',
    authDomain: 'caribe-6d583.firebaseapp.com',
    storageBucket: 'caribe-6d583.firebasestorage.app',
    measurementId: 'G-29LN325912',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADSCdPm9gRano6Jfm24zDELAnXeGk04hc',
    appId: '1:758475553455:android:8292d39ed0c309590a725a',
    messagingSenderId: '758475553455',
    projectId: 'caribe-6d583',
    storageBucket: 'caribe-6d583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtBkwTese6_eZE48CGLsA-8YIzxTKdqQs',
    appId: '1:758475553455:ios:1fb831e92e1b4c160a725a',
    messagingSenderId: '758475553455',
    projectId: 'caribe-6d583',
    storageBucket: 'caribe-6d583.firebasestorage.app',
    iosBundleId: 'com.example.caribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtBkwTese6_eZE48CGLsA-8YIzxTKdqQs',
    appId: '1:758475553455:ios:1fb831e92e1b4c160a725a',
    messagingSenderId: '758475553455',
    projectId: 'caribe-6d583',
    storageBucket: 'caribe-6d583.firebasestorage.app',
    iosBundleId: 'com.example.caribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj76cfiIgZRk_lpGhpHgvEqQp9jCX_1VY',
    appId: '1:758475553455:web:43673fc4361182b00a725a',
    messagingSenderId: '758475553455',
    projectId: 'caribe-6d583',
    authDomain: 'caribe-6d583.firebaseapp.com',
    storageBucket: 'caribe-6d583.firebasestorage.app',
    measurementId: 'G-97J5NVXPWE',
  );
}
